lsi: false
safe: true
source: https://github.com/sergetensen/sergetensen.github.io
incremental: false
highlighter: rouge
gist:
  noscript: flase
kramdown:
  math_engine: mathjax
  syntax_highligher: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
